### ISSUE TITLE
how to options the request to  do not check crt file

### ISSUE THREAD

**Issue by lcwxz1989** [ninenines/gun#101]
hi @essen    I am who have ask you the questhion, I think write the issue here will be better.  I have read the gun code , but I haven't found how to close the crt check option

**Comment by essen** [comment]
There's no check by default. Are you looking into enabling certificate validation?

**Comment by lcwxz1989** [comment]
@essen    I'm so sorry about I didn't talk the problem well
I have a https service A and working on port 8443
I also have a service B  useing http get method to connect to 8443
The problem is I thoght I must to close the B request crt validation to connect to 8443 . 
I can directly connect to 8443  without any options for crt validation, right?

**Comment by essen** [comment]
Yeah you can connect directly and no validation will be done (other than "did you send me a certificate or garbage"). Gun does not do any validation of the certificate authenticity out of the box.

**Comment by lcwxz1989** [comment]
Thank you , but what's the meaning of "did you send me a certificate or garbage"

**Comment by essen** [comment]
You still need a valid certificate (one that can be parsed properly), but self-signed is fine for Gun by default, at least today.

Closing, thanks!
