### ISSUE TITLE
Ability to transform headers before they are sent

### ISSUE THREAD

**Issue by strange** [ninenines/gun#115]
HTTP1 header names are supposed to be treated without regards to case. HTTP2 requires al header names to be lower case. Gun expects all header names to be lower case and depends on it in order to function correctly.

It would sound like the solution to the above is to simply lower-case all header names. But it is not that simple: many applications - and some servers - out there depend on the header name casing (see a similar discussion here: https://github.com/whatwg/fetch/issues/304).

The proposed solution (essen or IRC) is to give implementors the ability to transform header names via a callback before they are sent to a HTTP1 server.

**Comment by essen** [comment]
Done, thanks!
