### ISSUE TITLE
Lower case all header names

### ISSUE THREAD

**Issue by strange** [ninenines/gun#117]
Gun silently requires all header names to be in lower case to function correctly. All header names will be expected to be in lower case when HTTP2 catches on. It would therefore be nice if Gun automatically lower-cased all header names (with an option to disable this behavior).

**Comment by juise** [comment]
Plus one, spent about two hours to find out, why my header

`{<<"Content-Type">>,      "application/octet-stream"}`

doesn't work

**Comment by essen** [comment]
Doing this lowercasing in the calling process (inside gun) would also have the advantage that wrong inputs can be caught early with the appropriate stacktrace.

**Comment by essen** [comment]
I think it would be good to also accept string-list and atoms for the header names, then Gun can do the conversion immediately and it'd be compatible with all APIs. I don't think we care about iolists. I'll do all this now.

**Comment by essen** [comment]
Also should accept headers given as a map.

**Comment by essen** [comment]
Done, pushed, thanks!
