### ISSUE TITLE
SSE events dropped.

### ISSUE THREAD

**Issue by mm-tfx** [ninenines/gun#125]
Not sure if this is gun or cowboy or cowlib issue but it seems like something with gun.
I made loop_handler on cowboy side and it works. There is this idle_timeout issue and I wanted to try HTTP2 as you suggested.
I followed the example in sse_SUITE and I think I am missing something.
Gun stops receiving/parsing events sent from server after four events. (server sends those every second).
Now I have tried HTTP1 and it seems to work as intended.

What else I should check to find out why events are not being received after a while?

Thanks.

**Comment by essen** [comment]
What version of Cowboy is this? I fixed something similar there a few weeks ago.

**Comment by mm-tfx** [comment]
I fetched 1.0.0-pre.3 like week or two weeks ago.

**Comment by essen** [comment]
Asking about the Cowboy version, not Gun.

**Comment by mm-tfx** [comment]
Sure you asked about cowboy - I am using 2.0.0-pre.9 which I also fetched like week or two weeks ago.

**Comment by essen** [comment]
Now I remember. The fix for this specific issue is in https://github.com/ninenines/cowboy/commit/cad3e3f63d96559f16ee90e661a29063d0b3fc80 which was after 2.0.0-pre.9. Please try current master.
