### ISSUE TITLE
websockets & ssl

### ISSUE THREAD

**Issue by randysecrist** [ninenines/gun#129]
Is there any way to get gun to ws_upgrade a HTTP 1.1 socket that is using TLS/SSL?  (thus pinning the server to 1.1 instead of (what I'm guessing is ALPN selecting http2)?

Server is cowboy 2.0.

So far, it seems to just refuse the upgrade if I pass the ```transport :ssl``` option on ```gun:open```.

**Comment by essen** [comment]
I think you need the `protocols => [http]` option.

**Comment by randysecrist** [comment]
Yep, that does it.  Thanks!
