### ISSUE TITLE
handle a normal and shutdown messages in gun.erl

### ISSUE THREAD

**Issue by randysecrist** [ninenines/gun#130]
Before I submit a PR, I was wondering if you would be open to handling a few DOWN messages instead of letting the error_logger push them ...?

This is my proposed patch:
```
diff --git a/src/gun.erl b/src/gun.erl
index 3eafe10..7810d12 100644
--- a/src/gun.erl
+++ b/src/gun.erl
@@ -772,6 +772,10 @@ ws_loop(State=#state{parent=Parent, owner=Owner, socket=Socket,
                {system, From, Request} ->
                        sys:handle_system_msg(Request, From, Parent, ?MODULE, [],
                                {ws_loop, State});
+               {'DOWN', _MRef, process, _Pid, normal} ->
+                       ok;
+               {'DOWN', _MRef, process, _Pid, shutdown} ->
+                       ok;
                Any when is_tuple(Any), is_pid(element(2, Any)) ->
                        element(2, Any) ! {gun_error, self(), {notowner,
                                "Operations are restricted to the owner of the connection."}},
```

**Comment by essen** [comment]
Hm sounds like ws_loop is missing these lines to begin with: https://github.com/ninenines/gun/blob/master/src/gun.erl#L703-L706

So I think your patch needs to be improved. :-)

Also I'm not sure if we want to consider normal/shutdown (and `{shutdown,_}`, by the way) normal shutdowns as far as the Gun connection is concerned. Should we?

**Comment by randysecrist** [comment]
Ah, I see those lines above.  Y, I think adding those to the ws_loop would be good.  I'll do that and submit a PR.

As for your last question, I'm not sure I follow.  I am thinking about it tho.  Could you clarify?

**Comment by essen** [comment]
Well you seem to say that the owner process dying normally or via shutdown shouldn't be considered an error by Gun. I'm not sure whether that's the way to go. I'd like to hear more about your reasoning beforehand, like how Gun is used and why it would end up polluting error_logger (it probably would even with the missing clause, via the supervisor of the Gun process).

**Comment by randysecrist** [comment]
The use case is this;

I have a websocket API I want to test from ExUnit.  ExUnit spawns a process for each test and also runs the cleanup function in a different process from the test itself.

So the shutdown function gets called from a different process which owns the connection; and the owner is dead.  https://gist.github.com/randysecrist/348015b8ee32d1a90978ff68b0595be4#file-test_case-ex-L1-L11

The full gist is here;
https://gist.github.com/randysecrist/348015b8ee32d1a90978ff68b0595be4

**Comment by essen** [comment]
I went to look into the logs of test suites I ran, and I can indeed see these messages too. I never noticed before.

OK.

* We should definitely add the missing clause for Websocket.
* We should probably handle the `normal`, `shutdown` and `{shutdown, _}` reasons differently than other reasons (which would be considered errors).
* How we handle these will probably differ depending on the protocol; maybe we'll want to send a close (Websocket) or GOAWAY (HTTP/2) frame with a different error code when an error occurs, maybe not

**Comment by essen** [comment]
I will go ahead with adding the missing clause, as I need it for a customer. We can discuss further about the behavior we want for normal/shutdown exit reasons.

**Comment by randysecrist** [comment]
I found that by adding the missing clause the error log was cleaned up.  I'm not sure what normal/shutdown exit reasons should be; definitely something to think about.

**Comment by essen** [comment]
No I just did.

Leave the ticket open, there is some extra work to do for normal/shutdown. It *will* still pollute logs, but only if sasl is enabled (via supervisor reports).

**Comment by essen** [comment]
Should be totally fixed!
