### ISSUE TITLE
Support for comms via Unix domain sockets

### ISSUE THREAD

**Issue by sanmiguel** [ninenines/gun#134]
Since R19 we've had some support for opening unix domain sockets in erlang/otp. The underlying transport libraries support this, but it requires a little acrobatics to get everything working which is unfortunately precluded from working with `gun` as-is because of the `is_list(Host); is_atom(Host)` check in `gun:open/3`.

The minimum change would be to allow passing in a tuple `{local, SocketPath}` with a check for `is_list(SocketPath) ; is_binary(SocketPath)`. However that leaves more work for users to do:

- `Port` must be 0
- each request must manually pass the header `{<<"host">>, <<"localhost">>}`

I have [a branch](https://github.com/sanmiguel/gun/tree/http_unix_sockets) on which I've added a separate function, `gun:open_unix/2` that at least deals with the Host and Port. I'll submit a tentative PR shortly from it and we can take it from there.

**Comment by essen** [comment]
Separate function sounds good.
