### ISSUE TITLE
GET request with body is possible.

### ISSUE THREAD

**Issue by refactor** [ninenines/gun#136]
It seems GET method can carry body, when I use elasticsearch, I found it use tons of GET request with body, which carry DSL query.

"Both HTTP GET and HTTP POST can be used to execute search with body. Since not all clients support GET with body, POST is allowed as well."

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html

**Comment by essen** [comment]
Sure? I don't think Gun restricts this in any way. Just use gun:request if you want to do something exotic.
