### ISSUE TITLE
How to let await return error after canceled?

### ISSUE THREAD

**Issue by tony612** [ninenines/gun#144]
I want to return an error if `:gun:await/2` is called after the HTTP/2 stream is canceled. Is there any way to achieve this? Like getting the canceled status?

**Comment by essen** [comment]
It should return an `{error, Reason}` tuple in that case. Doesn't it?

**Comment by tony612** [comment]
Yes. Now it will wait forever or until timeout.

**Comment by essen** [comment]
When you say canceled do you mean that you cancel the stream on the client side or that the server cancels the stream?

**Comment by tony612** [comment]
On the client side, after calling `:gun:cancel/2`. Of course I know I shouldn't try to send data after canceling, but I want to know the status of the stream in some way.

**Comment by essen** [comment]
Ah OK it makes more sense then, I thought you meant the server.

I'm not sure it's possible because `gun:await` only does a receive. On the other hand maybe what we can add is a separate function to query a stream's state so that you can know whether an await call will have chances of succeeding.

**Comment by tony612** [comment]
Yeah, I think adding a function will be a good solution so that we don't need to change how `gun:await` behaves.

**Comment by essen** [comment]
I've just added `gun:stream_info/2` and it will be in 2.0. Closing, thanks!
