### ISSUE TITLE
A different result between the document and a program about `gun:ws_upgrade`

### ISSUE THREAD

**Issue by niku** [ninenines/gun#146]
Hi, I found a different result between the document and a program when It was executed `gun:ws_upgrade`.

[The document](https://github.com/ninenines/gun/blob/a00a6b2d047a5d41e8e062d1c414000b000b45d7/doc/src/manual/gun.asciidoc#ws_upgradeconnpid-path-headers-wsopts--ok) indicates `gun:ws_upgrade` returns `ok`.
However, a program indicates `gun:ws_upgrade` returns a type of `Reference`:

```erl
/Users/niku/src/gun% git log --oneline -1
a00a6b2 (HEAD -> master, origin/master, origin/HEAD) Enable ci.erlang.mk only when CI_ERLANG_MK=1 is set
/Users/niku/src/gun% rebar3 shell --apps gun
===> Verifying dependencies...
===> Compiling gun
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:0] [hipe] [kernel-poll:false] [dtrace]

Eshell V9.3  (abort with ^G)
===> The rebar3 shell is a development tool; to deploy applications in production, consider using releases (http://www.rebar3.org/docs/releases)
===> Booted cowlib
===> Booted ranch
===> Booted gun
1> {ok, ConnPid} = gun:open("echo.websocket.org", 80).
{ok,<0.149.0>}
2> {ok, http} = gun:await_up(ConnPid).
{ok,http}
3> X = gun:ws_upgrade(ConnPid, "/").
#Ref<0.2170381907.506462209.18502>
4>
```

Which result is intended one?

**Comment by essen** [comment]
The code is correct. The documentation was supposed to have been updated in a separate commit but I suppose this was either not done or this particular issue was missed.

**Comment by niku** [comment]
Thank you for your quick reply.

Can I send a PR to fix the document?

**Comment by essen** [comment]
Yes please.

**Comment by essen** [comment]
Thanks!
