### ISSUE TITLE
gun:await_up/1 timeout when host is IP string

### ISSUE THREAD

**Issue by seudin** [ninenines/gun#152]
Hi,

gun:await_up/1 timed out when call gun:open("10.1.1.1", 443).

gun:do_open wrong handle error returned by runch_ssl:connect. All errors are handled by retry what leads to timeout.

ranch_ssl:connect("10.1.1.1", 443, [], 5000).
{error,{options,{{server_name_indication,"10.1.1.1"}}}}
but
ranch_ssl:connect({10,1,1,1}, 443, [], 5000).
works correctly.

ranch_ssl:connect allow Host parameter to be type of hostname() or  ipaddress(), but gun:open doesn't accept ipaddress() for Host parameter.

Solution will be to allow  gun:open/{2,3} to accept ipaddress() for Host too, so user can use inet:parse_address if needed.
It will be usefully to return/log errors from ranch_ssl/tcp not related to timedout.

Above is tested on branch master and Erlang 20.1.

Kind regards.

**Comment by essen** [comment]
Where does `{error,{options,{{server_name_indication,"10.1.1.1"}}}}` come from? Neither Gun nor Ranch set this option.

**Comment by seudin** [comment]
It comes from ssl:connect("10.1.1.1", 443, [], 1000) called by ranch_ssl:connect.

**Comment by essen** [comment]
Does the server require SNI perhaps? In that case you'd need to provide the correct transport options.

**Comment by essen** [comment]
Try tracing to see what's happening. Cowboy is tested using Gun via SSL and I do not have this so I'm unlikely to reproduce without more details.

**Comment by seudin** [comment]
I did. But connection never come to server. The problem is misconfigured ssl:connect.

If I change spec to allow inet:ipaddress() and guard to allow tuple of gun:open then it works.

`diff --git a/src/gun.erl b/src/gun.erl
index f628199..a4ef417 100644
--- a/src/gun.erl
+++ b/src/gun.erl
@@ -125,14 +125,14 @@

 %% Connection.

--spec open(inet:hostname(), inet:port_number())
+-spec open(inet:hostname() | inet:ipaddress(), inet:port_number())
        -> {ok, pid()} | {error, any()}.
 open(Host, Port) ->
        open(Host, Port, #{}).

--spec open(inet:hostname(), inet:port_number(), opts())
+-spec open(inet:hostname() | inet:ipaddress(), inet:port_number(), opts())
        -> {ok, pid()} | {error, any()}.
-open(Host, Port, Opts) when is_list(Host); is_atom(Host) ->
+open(Host, Port, Opts) when is_list(Host); is_atom(Host); is_tuple(Host) ->
        do_open(Host, Port, Opts).

 -spec open_unix(Path::string(), opts())`

**Comment by essen** [comment]
I'm OK accepting a PR allowing IP tuples if that solves your problem.

**Comment by essen** [comment]
Thanks!
