### ISSUE TITLE
Timeline on stable hex release?

### ISSUE THREAD

**Issue by ospaarmann** [ninenines/gun#157]
Hey there,

first of all thank you for providing gun ❤️ 

I wanted to ask if there is a timeline for a stable release on hex.pm since rc1 is out on GitHub. The reason I'm asking is that https://github.com/tony612/grpc-elixir depends on it and cannot do a stable release with unstable dependencies or dependencies from GitHub. And my Elixir Dgraph client https://github.com/ospaarmann/exdgraph depends in turn on tony612/grpc-elixir. I still have two issues to fix but after that I would love to do a stable release on hex.

If you need any support please let me know how I can help.

Cheers,
ole

**Comment by essen** [comment]
1.0 will be released once I have confirmed the rc works at customer and I do not have a timeline for that yet unfortunately.

**Comment by essen** [comment]
I've tagged 1.0.0. @petrohi will take care of hex I think. Announcement is coming. Closing!
