### ISSUE TITLE
Crash when http2 server closes connection

### ISSUE THREAD

**Issue by taavi013** [ninenines/gun#177]
Just open connection and wait 10+ seconds:
gun:open("dns.google.com", 443).

`[error] Supervisor gun_sup had child gun started with {gun,start_link,undefined} at <0.923.0> exit with reason no function clause matching gun_http2:parse(<<>>, close) line 106 in context child_terminated`

**Comment by essen** [comment]
I'm currently reworking the HTTP/2 code by merging the Cowboy and Gun code together. If you can send a PR with a test case for this I can make sure to fix it while I do the changes on Gun.

**Comment by taavi013** [comment]
Sorry for false alarm, gun from master works. Reopens connection, etc.
Was using gun from rebar3 without indicating version.
