### ISSUE TITLE
What does :shutdown mean?

### ISSUE THREAD

**Issue by 9mm** [ninenines/gun#179]
I randomly get this for some high volume requests but I can't pin down where this is from? what is going wrong?

**Comment by essen** [comment]
If it's just a shutdown exit reason, it just means the owner process is gone for reason shutdown.

**Comment by 9mm** [comment]
Can you think of any reason why Elixir/Erlang would do that? All I'm doing is ~20-30 requests per second and I randomly get `:shutdown` but there's no other information about it. I am trying to trace where/why its happening

**Comment by petrohi** [comment]
@essen you may close this one--issue is in machine_gun
