### ISSUE TITLE
Update cowlib to 2.7.0

### ISSUE THREAD

**Issue by wdavies973** [ninenines/gun#186]
Currently trying to use cowboy (for websockets with client connections) and gun (for websockets with other servers) at the same time. When running `mix deps.get`, it complains about cowboy using `cowlib 2.7` while gun is using `cowlib 2.6`. Not sure if it's safe to override and using 2.7 for both or 2.6 for both.

Would you be able to update `cowlib` or at least let me know if 2.7 & 2.6 are cross compatible?

Thanks!

**Comment by essen** [comment]
Yes it's safe to override, just make sure to use the most recent version. I'm working on a Gun update but it's a big one so it'll take a while.

**Comment by mackeyja92** [comment]
Can we please update this dep? Or at least specify greater than version in the deps?

**Comment by essen** [comment]
Gun currently depends on Cowlib master so?

**Comment by xinz** [comment]
Hi,

Currently, the latest [gun](https://hex.pm/packages/gun) is `1.3.2` with `cowlib ~> 2.6.0`, but  the major versions used of cowboy is `2.7.0` with `cowlib ~> 2.8.0`, in this case there exists a conflict when use the deps.

 @essen, could you please help on this to release a new version 1.x of `gun` to update the `cowlib`?

Thanks in advanced!

**Comment by essen** [comment]
I have no plans for a new 1.x release at this time. 1.3.2 was done to fix an issue a customer was facing. I will only do more 1.x releases if a paying customer is asking.

Also note that I'm not the Hex package author.

**Comment by xinz** [comment]
Hello @essen thanks for your reply, I'm glad to be able to sponsor you, thank you for your contribution to the open source projects, which only represents a little of my heart.

Anyway, if there is an available gun version of 1.x, there will helpful for the community users.

Thanks!

**Comment by essen** [comment]
Thanks and sorry but the tier in question for maintaining old versions or requesting releases in general is the 4th tier, though you can get a one-off release at lower prices by contacting me directly. Expect at least 500€ to pay for the time needed to make and test a release. Feel free to cancel the Github sponsor if that's not the answer you were looking for.

**Comment by xinz** [comment]
Sorry that I didn't take the details of tiers carefully, I will try to find another way for my use case.

Let me buy you some drink 🍺 ：）

**Comment by essen** [comment]
Cheers.
