### ISSUE TITLE
Do you plan a 1.4 release or can I consider master as stable now?

### ISSUE THREAD

**Issue by GuillaumeMilan** [ninenines/gun#202]
Hello, 
I am currently trying to use the function: `gun:ws_upgrade` on a socket open on an `ip6_address()`. 
But as you have fixed on master, there were a bug on the payload formation in the released version 1.3 of `gun`. 

So my question is: 
Do you plan to make a new release (1.4 maybe) of the gun package. Or do you think master is now stable enough to be used as it is. 

Sorry if it is not the location to ask this question, I am a bit new to the erlang community and I do not know to contact you.

**Comment by essen** [comment]
The current work on master is going toward the 2.0 release. There's been some breaking changes on master already (but most people are not going to encounter them). There's been a lot of work done but a lot is left to do. Currently working on #151.

**Comment by essen** [comment]
2.0 is out.
