### ISSUE TITLE
Empty String for Body

### ISSUE THREAD

**Issue by randysecrist** [ninenines/gun#211]
Just a question ...

Is it possible to use a empty string (`""`) as a post body with gun?  I wrote a test case the other day using gun and if I recall correctly gun:await was returning `{:error, :timeout}` ... so I ended up skipping that test case...

(note cowboy handles empty string just fine - (`curl -d "" works`); it seems to be just client side using gun)

**Comment by essen** [comment]
In the 1.x version there was a design issue that could cause confusion, if you used an empty body but had a content-type or similar header Gun still expected a body afterwards. This is fixed in 2.0.0-pre.1.
