### ISSUE TITLE
settings_timeout when connecting elixir grpc to python server

### ISSUE THREAD

**Issue by mairbek** [ninenines/gun#215]
We are observing periodic `{:cow_http2_machine, :settings_timeout}` error messages when trying to connect from elixir grpc to python server.

See more details in the original issue https://github.com/elixir-grpc/grpc/issues/132

**Comment by mairbek** [comment]
Any updates? This blocks our [ @brexhq ] migration to gRPC

**Comment by essen** [comment]
I have not prioritized it yet.

Why does this block your migration? This is just a message being logged. Note that the fix for this is to make Gun close the connection, so either way it seems you'll want to increase the timeout value if your server is too slow.

**Comment by essen** [comment]
Fixed in 1b7b5ca356609574dac30dbec846dbd75718624e. Thanks!
