### ISSUE TITLE
Should return all body when content-length and transfer-encoding aren't present

### ISSUE THREAD

**Issue by unix1** [ninenines/gun#22]
Currently when gun gets a 200 response that:
* does *not* contain ```content-length```
* does *not* contain ```transfer-encoding```

it cuts the server response off after ```head```. See ```gun_http:io_from_headers/2```.

Expected behavior would be that it returns received body message until server closes connection.

Here's why:
Per http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4
1. Response that may include body, e.g. 200
2. transfer-encoding is not present
3. content-length is not present
4. message doesn't use multipart/byteranges media type
then
5. client must determine message length by server closing connection

So the proposed fix, since gun doesn't yet track (1) above, maybe it should assume body may be present and change ```head``` to ```body_close``` when ```lists:keyfind(<<"transfer-encoding">>, 1, Headers)``` is ```false```.

Alternatively, I'm way off and @essen will set me straight.

**Comment by essen** [comment]
This is done, wooo!
