### ISSUE TITLE
MatchError in :gun.info/1

### ISSUE THREAD

**Issue by alex-strizhakov** [ninenines/gun#222]
Hey!
Sometimes in logs i see `MatchError` for `:gun.info/1` calls.
```
** (MatchError) no match of right hand side value: {:error, :einval}
(gun 2.0.0-pre.1) /home/pleroma/deps/gun/src/gun.erl:434: :gun.info/1
```

Gun is used from master branch and `:gun.info/1` is called after `:gun_up` message. Not quite sure what is causing this.

**Comment by essen** [comment]
Makes sense, `Transport:sockname/1` isn't guaranteed to succeed, for example if the socket is not connected. In that case it should act like `undefined` I think, meaning the ip/port would not be included in the info (we don't have them anyway).

https://github.com/ninenines/gun/blob/74ac4d209c86f64059b1eaa0e541eb7d26dd23a8/src/gun.erl#L434

**Comment by alex-strizhakov** [comment]
Sounds good

**Comment by essen** [comment]
I will do this change and prepare a new pre-release on Wednesday.

**Comment by essen** [comment]
Done locally, push soon. Thanks!
