### ISSUE TITLE
Any plan to release 2.0?

### ISSUE THREAD

**Issue by tony612** [ninenines/gun#229]
gRPC depends on Gun 2.0 heavily. Is there a plan to release a stable 2.0 version? Thank you!

**Comment by essen** [comment]
You're welcome to sponsor the release if you want. Plans are to do a `pre.3` before RCs.

**Comment by mackeyja92** [comment]
Also looking forward this release.

**Comment by sorliem** [comment]
I am also looking forward to this release.

**Comment by essen** [comment]
Feedback on the RC is welcome.

**Comment by kdawgwilk** [comment]
@essen Anything the community can do to help test/prep for the 2.0 release?

**Comment by polvalente** [comment]
@essen How can we help with the 2.0 release? Is there a roadmap somewhere with what's missing in 2.0.0-rc.2?

**Comment by essen** [comment]
Taking on https://github.com/ninenines/gun/pull/243#discussion_r824856311 would help. Small PRs to move this forward.

I will have some time in August to finish my work on the cookie test suites and make sure everything is up to date with specs.

**Comment by essen** [comment]
It's out.
