### ISSUE TITLE
Error case_clause in gun:connecting/3

### ISSUE THREAD

**Issue by zuiderkwast** [ninenines/gun#253]
When I run the test suites on current master, I get a `{case_clause, {ok, #Port<0.16>}}` error in `gun:connecting/3` [(gun.erl, line 1061)](https://github.com/ninenines/gun/blob/d5f1a47/src/gun.erl#L1061).

It happens in the test case `event_SUITE:tls_handshake_end_error_tls_connect_tls/1`. The guards prevent matching because the local variable `Transport` is `gun_tls_proxy`. The guards here are expecting it to be either `gun_tcp` or `gun_tls`.

**Comment by essen** [comment]
Yes I know. There's a todo in the disconnect function.

**Comment by zuiderkwast** [comment]
Ah, didn't see that.

**Comment by essen** [comment]
This is important to fix for 2.0 but not for 2.0.0-rc.1 so I will probably skip it for now.

**Comment by essen** [comment]
I've fixed it. There's still some crashes in event_SUITE though but they're covered by #248 (lack of error handling). I'll see if I can fix it.

**Comment by essen** [comment]
For future reference the other issue in `event_SUITE` is a bug in Cowboy: https://github.com/ninenines/cowboy/issues/1479
