### ISSUE TITLE
gun_down missing StreamRef in websocket connection

### ISSUE THREAD

**Issue by benbro** [ninenines/gun#265]
The [manual](https://ninenines.eu/docs/en/gun/2.0/manual/gun_down/) says that gun_down should have a list of killed streams but I'm getting an empty list. I'm using recent commit in the master branch.
```erlang
{gun_down, ConnPid, Protocol, Reason, KilledStreams}
KilledStreams      :: [gun:stream_ref()]
```

**Comment by essen** [comment]
When using Websocket over HTTP/1.1 Gun should return a list containing the Websocket's StreamRef.

**Comment by benbro** [comment]
Sometimes I'm getting an empty list and sometimes getting the Websocket's StreamRef.

**Comment by essen** [comment]
Fixed, thanks!
