### ISSUE TITLE
Timeframe for 2.0.0

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [ninenines/gun#268]
Hi. First of all, thanks for `gun`. This is not a complaint, a bug or a feature request, but a request for information 😄. We've been depending on `gun` 2.0.0-rc.1 for a while now and were wondering when you expect 2.0.0 to come out, now that OTP 24.0 is also out. This is especially important so that we depend on a "stable" reference and so that some other lib.s we use (that depend on `gun`) also benefit from that. Feel free to close the issue after replying if you feel it's not relevant to keep it open until the version is out.

**Comment by essen** [comment]
It's mostly a matter of finding the time to finish up. It would help if people were running the current master as there's been larger last minute changes (`gun_pool`). Perhaps I will cut an rc.2 to help with that.

**Comment by paulo-ferraz-oliveira** [comment]
> Perhaps I will cut an rc.2 to help with that.

That'd be nice.

**Comment by lhoguin** [comment]
Should remove this as it's no longer necessary. Might be more in other files: https://github.com/ninenines/gun/blob/master/src/gun.erl#L18-L20

**Comment by NelsonVides** [comment]
What about a hex package that can compile with OTP24 as well? Perhaps a 2.0 can be released with a clear documentation of the use cases not implemented yet, and later on a finalised 2.1 release can go?

**Comment by essen** [comment]
Everything is implemented and I've recommended people use 2.0 for some time.

**Comment by paulo-ferraz-oliveira** [comment]
@NelsonVides, I wrote (initial description) "now that OTP 24.0 is also out" and it's why I waited to do this request, here.

IIRC, `gun` already IS 24-ready, it's just not tagged 😄

**Comment by essen** [comment]
I have released 2.0.0-rc.2 please test and provide feedback. Bonus points if you can test gun_pool as well but that's not required for this release as it's still experimental.

**Comment by jb3** [comment]
We've tested rc2 in [Kraigie/nostrum](https://github.com/Kraigie/nostrum) for a little while and all seems well.

Is there any news on when this is released? We've been able to dumb down a lot of logic with the rc so would love to be able to get it out.

**Comment by essen** [comment]
I think it's good to go so it's just a matter of reviewing the PRs/tickets and do the release. It'll take some time as I am busy with other things. But I will soon be doing some benchmarking so I will have some free time to fill.

In any case I'm closing this ticket, feel free to open a discussion instead if you want.

**Comment by essen** [comment]
It's out.
