### ISSUE TITLE
gun 2.0 RC ready?

### ISSUE THREAD

**Issue by cdesch** [ninenines/gun#306]
`gun` has been in the Release Candidate version ` 2.0.0-rc.2` for some time now. Is there something that is holding it back from going to `2.0.0` and rolling the rest into patch level fixes?

[`{:gun, "~> 2.0.0-rc.2"}`](https://hex.pm/packages/gun)

**Comment by paulo-ferraz-oliveira** [comment]
Also refer to:

* [gun: Any plan to release 2.0?](https://github.com/ninenines/gun/issues/229)
* [gun: Timeframe for 2.0.0](https://github.com/ninenines/gun/issues/268)

for more information.

**Comment by essen** [comment]
https://github.com/ninenines/gun/milestone/1

I expect the release to happen before the end of the year.

**Comment by essen** [comment]
Assuming nothing breaks badly, next week. Closing, thanks!

**Comment by essen** [comment]
Unfortunately I'm the one who broke. I've been too sick to work for the past few days. I'll have to push this back one more week.

**Comment by essen** [comment]
It took a while but I now have a green Cowlib build. OTP-25 broke a number of things in CI and that took time to fix. So next week I expect to release the new Cowlib version needed by Gun 2.0. Whether I can release Gun 2.0 at the same time will depend on free time available.

**Comment by essen** [comment]
It's out.
