### ISSUE TITLE
Crash during termination when connecting to a server requiring mTLS over HTTP/2

### ISSUE THREAD

**Issue by voluntas** [ninenines/gun#313]
I have been encountering a crash during termination when I try to connect to a server that requires mTLS via HTTP/2.

When using HTTP/2 to connect, if the server requires mTLS, it appears to fail at Protocol:init in this section, leaving protocol as undefined and proceeding to the disconnect step:
https://github.com/ninenines/gun/blob/master/src/gun.erl#L1259-L1263

Following this, in the disconnect step, it attempts to call undefined:close, which ultimately leads to a crash:
https://github.com/ninenines/gun/blob/master/src/gun.erl#L1742

As I'm not sure how to properly address this, I decided to start by creating an issue here.

**Comment by essen** [comment]
With mTLS you have to send the client's certificate I believe and I don't see it configured in your snippet. You will likely need to set `{verify, verify_peer}, {cacerts, ...}, {cert, ...}` and maybe a few more options.

**Comment by essen** [comment]
Ah fair enough.

Hmm I suppose a trace on the module `gun` would help (set it up before gun:open) because I do not see how this could happen from looking at the code. Also please ensure that this is the most recent Gun version just in case.

```
dbg:tracer().
dbg:tpl(gun, []).
dbg:p(all, c).
gun:open(...)
```

**Comment by essen** [comment]
If `ssl:negotiated_protocol/1` was returning `{error, closed}` the crash would be earlier. The documentation for the function shows that it cannot return `{error, closed}`: https://www.erlang.org/doc/man/ssl.html#negotiated_protocol-1 - have you seen a crash there or just the bad certificate error?

The fix would be to set the protocol value before calling disconnect as you mention. Did you try and see if that fixes it?

**Comment by essen** [comment]
OK that's where we can get a `closed` error: https://github.com/erlang/otp/blob/master/lib/ssl/src/ssl_gen_statem.erl#L1318-L1329 - probably a documentation issue in OTP, I will send a PR later.

As for what to do when gun_http2:init fails, I think calling `disconnect` is not the right thing to do. We failed to establish a connection so we should go back to `not_connected` like if there was a TCP error. I'll try and see if I can get something I can reproduce so I can write a test for it.

**Comment by essen** [comment]
I can reproduce, thanks. But only if I use a timer:sleep after the connect. So I will have to do that in my tests (the tls_handshake_end event can be used to do the timer:sleep and/or call negotiated_protocols again). So now it's just a matter of finding the time to do the patch. Thanks!

**Comment by essen** [comment]
I'm close to having finished, I just need to replace the shiguredo server with something local in the tests I wrote.

I cannot test ssl:negotiated_protocol behavior in the test suite but I fixed it manually and it's probably not as much of an issue without timer:sleeps.

**Comment by essen** [comment]
Done, thanks!
