### ISSUE TITLE
Add Socks5 proxy Support

### ISSUE THREAD

**Issue by edescourtis** [ninenines/gun#32]
Please consider adding HTTP proxy and Socks5 proxy (with and without remote DNS resolution). Many applications require at least Socks Proxy support. If choosing is necessary Socks5 would be good enough for most use cases.

**Comment by essen** [comment]
I will add CONNECT in the near future (about the same time I add it to Cowboy), perhaps that will be enough? Or do you need something else?

**Comment by edescourtis** [comment]
Socks5 is perfect. I guess the only other useful thing would be that the hostname resolution can be done remotely (perhaps as an option). That would enable the us to use it with anonymization services or where no DNS access is available.

**Comment by edescourtis** [comment]
Thanks for adding this. I might add Socks5 later if I have the time.

**Comment by essen** [comment]
Yeah I would be interested to add SOCKS5 but I don't really have anything to test it against. I will be adding CONNECT soon because I am working my way through the new HTTP RFCs writing test suites and CONNECT is part of them.

**Comment by edescourtis** [comment]
You might want to test against tor. It hosts a Socks5 proxy by default over port 9050.

**Comment by essen** [comment]
Note that CONNECT support was added in 1.2 and will be corrected (for HTTP/2 over TLS) in 1.3.

**Comment by essen** [comment]
The relevant specs for SOCKS5 are:

* https://tools.ietf.org/html/rfc1928
* https://tools.ietf.org/html/rfc1929
* https://tools.ietf.org/html/rfc1961
* https://tools.ietf.org/html/rfc3089 (informational)

And for SOCKS4:

* http://ftp.icm.edu.pl/packages/socks/socks4/SOCKS4.protocol

**Comment by essen** [comment]
Also related would be the ability to send PROXY protocol headers. Maybe what's needed in both cases is a separate protocol module that does its thing and then switch to `gun_http` or other. In the PROXY case it would need to switch right after init because all it does is send and then optionally initiate the TLS handshake.

**Comment by essen** [comment]
The PR #208 now can do Socks5 over TCP/TLS to connect to HTTP 1/2 servers running TCP/TLS. I will be adding a few more tests and then merge into Gun proper and create a 2.0 pre-release with it.

**Comment by essen** [comment]
I've merged the PR. It's still lacking a good handling of error conditions and there's some open questions (should there be an event? probably) but the remaining work can be done in master. Closing, thanks!
