### ISSUE TITLE
client_preferred_next_protocols is incompatible with TLS 1.3

### ISSUE THREAD

**Issue by JeppeTh** [ninenines/gun#323]
It's not possible to run TLS 1.3 only for Gun since client_preferred_next_protocols is incompatible. 
You get

                           {error,
                            {options,dependency,
                             {client_preferred_next_protocols,
                              {versions,[tlsv1,'tlsv1.1','tlsv1.2']}}}}},

when trying. I.e. should avoid providing this one if versions are ['tlsv1.3'].

**Comment by essen** [comment]
This was fixed in Gun 2.1. Thanks!
