### ISSUE TITLE
{down, noproc} error on gun:post

### ISSUE THREAD

**Issue by IgorKoshnarov** [ninenines/gun#339]
Hello! 
We use gun 2.0.0, erlang 23.
The problem is that we get quite a few occasional errors {down, noproc} among successful responses on post requests:

```
    StreamRef = gun:post(Connection, Path, Headers, Body),
    gun:await(Connection, StreamRef, Timeout),
    gun:await_body(Connection, StreamRef, Timeout)
```

The connection is made like this:
```
    ConnectionOpts = #{
        retry => 3,
        retry_timeout => 1000,
        http_opts => #{keepalive => 5000},
        connect_timeout => 3000
    },
    gun:open(Host, Port, ConnectionOpts)
```
We reuse established connection for several http requests to the same host, have added monitor and reestablish new one when get 'DOWN' message from the previous one.
```
   Ref = erlang:monitor(process, Connection).
```

```
    handle_info({'DOWN', Ref, process, Pid, Reason}, State) ->
        reconnect().
```

**Comment by essen** [comment]
Add an event handler, log all events, and you'll see why the connection goes down.

**Comment by IgorKoshnarov** [comment]
It was the bug in our custom pool implementation, the broken connection was not deleted from pool, thanks for help!
