### ISSUE TITLE
Implement auto ping for Websocket

### ISSUE THREAD

**Issue by essen** [ninenines/gun#46]
We have one for the HTTP/SPDY part, but not for Websocket.

Should probably be different options.

**Comment by marjaimate** [comment]
@essen is this included already in any of the pre releases?

**Comment by essen** [comment]
No it has not been added yet. If the server sends a ping, Gun will respond. But Gun will not send a ping on its own in the current code.

**Comment by essen** [comment]
Done in d9a970be90d0105af215531d74809878f9c21338.
