### ISSUE TITLE
Add support for SSE

### ISSUE THREAD

**Issue by essen** [ninenines/gun#48]
Should be a short task.

**Comment by joustava** [comment]
any updates on this one?

**Comment by essen** [comment]
No. :-)

**Comment by joustava** [comment]
any tips for one who might have a look at getting it to work?

**Comment by essen** [comment]
SSE is a very simple protocol, Gun can receive streamed bodies (more or less), SSE is just a little parsing on top of that. In a customer project I simply do it in that project's side rather than in Gun itself. But native support would be nice.

**Comment by essen** [comment]
It's done, by the way. Not documented yet but there's a new content_handlers protocol option.
