### ISSUE TITLE
Gun is silent on errors

### ISSUE THREAD

**Issue by essen** [ninenines/gun#57]
And this should probably be improved.

For example when a connection failure happen and Gun gives up reconnecting it is fairly hard to debug.

**Comment by jtmoulia** [comment]
This is a rough edge that's been bugging me. If no one else is working on this, I can take a crack at it.

There's an outline of the reqs in #13.

**Comment by essen** [comment]
I'm not exactly sure about it but feel free to experiment.

**Comment by essen** [comment]
That part is good enough as per Twitter. The connection up/down is still to be done. Closing, thanks!
