### ISSUE TITLE
Add Websocket protocol negotiation

### ISSUE THREAD

**Issue by essen** [ninenines/gun#63]
Options are needed, code also, and guide of course.

**Comment by mururu** [comment]
I need this. Is there any progress here?

**Comment by essen** [comment]
You can set/check the headers directly currently. This ticket is for a more automated way.

**Comment by mururu** [comment]
The headers seems to be ignored because the `Headers` here is not merged.

https://github.com/ninenines/gun/blob/master/src/gun_http.erl#L391-L416

**Comment by essen** [comment]
Good catch!

**Comment by essen** [comment]
Pushed a different Should be good on current master now. Thanks!

I do not think I will add more with regard to Websocket, since we can both send and receive headers now. Closing, thanks!
