### ISSUE TITLE
Disable keepalive by default for HTTP/1.1?

### ISSUE THREAD

**Issue by essen** [ninenines/gun#67]
Either 'false' or 'infinity' should work to disable it. Leaning toward 'false' as 'infinity' is a bit unclear.

**Comment by adrianroe** [comment]
As gun is heading towards 1.0 it would be nice to have this sorted - my personal take would be to change the default to not have keepalive at all (i.e. to only send the CRLFs is the config explicitly requests them).  The extra messages certainly don't play well with e.g. AWS REST endpoints and http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4 has strong (negative) opinions on the subject...


4.1 Message Types

HTTP messages consist of requests from client to server and responses from server to client.

       HTTP-message   = Request | Response     ; HTTP/1.1 messages
Request (section 5) and Response (section 6) messages use the generic message format of RFC 822 [9] for transferring entities (the payload of the message). Both types of message consist of a start-line, zero or more header fields (also known as "headers"), an empty line (i.e., a line with nothing preceding the CRLF) indicating the end of the header fields, and possibly a message-body.

        generic-message = start-line
                          *(message-header CRLF)
                          CRLF
                          [ message-body ]
        start-line      = Request-Line | Status-Line
In the interest of robustness, servers SHOULD ignore any empty line(s) received where a Request-Line is expected. In other words, if the server is reading the protocol stream at the beginning of a message and receives a CRLF first, it should ignore the CRLF.

Certain buggy HTTP/1.0 client implementations generate extra CRLF's after a POST request. To restate what is explicitly forbidden by the BNF, an HTTP/1.1 client MUST NOT preface or follow a request with an extra CRLF.

**Comment by edgurgel** [comment]
This [commit](https://github.com/ninenines/gun/commit/0fe54af72b81fdb198a377198d7f3a91f9ad6d7c) fixed this right?

**Comment by essen** [comment]
There's still the discussion about the default value I guess.

**Comment by essen** [comment]
Default has been set to infinity locally and that will be for Gun 2.0.
