### ISSUE TITLE
Provide a Release

### ISSUE THREAD

**Issue by elbrujohalcon** [ninenines/gun#69]
Seeing [this page](https://github.com/ninenines/gun/releases) so empty breaks my heart :trollface:.
Can you please provide a release for us there, @essen? :)

**Comment by Euen** [comment]
+1

**Comment by jfacorro** [comment]
+1

**Comment by davecaos** [comment]
+1

**Comment by essen** [comment]
I am currently working on 1.0 and we (me and sponsors) have decided that this release will be for Erlang 18+. The only tag I am planning at this point is just before I make Gun require 18+ as 18 won't be out yet. Sorry but you'll have to wait.

**Comment by andreaskern** [comment]
Can we have 0.9.0 tag with this commit cf3fbe19e3d19a40e0a1d15d8e36db3169a5c649
i'm trying to merge a proxy protocol parser into cowboy 1.0.1 but the cowboy tests fail miserably. They depend on the master branch.

another workaround I did was to fork gun and introduce a stable branch pointing to cf3fbe19e3d19a40e0a1d15d8e36db3169a5c649.

**Comment by essen** [comment]
I am working on fixing the Cowboy tests. I have about 10 or so left to fix now. Should probably be done next week.

**Comment by essen** [comment]
I made a tag 1.0.0-pre.1. More will likely follow before the switch to 18+.

This tag is used to test Cowboy (yet to be pushed though) and everything passes successfully.

Enjoy!
