### ISSUE TITLE
After down connection first retry must happen immediately

### ISSUE THREAD

**Issue by unix1** [ninenines/gun#70]
Currently, when the server closes the HTTP connection, gun client attempts to retry opening the connection, but the first such attempt happens `retry_timeout` time after the connection close. Instead, the first retry should happen immediately, and only subsequent retries happen `retry_connection` time later.

Rough details of current implementation:
- `down|connect`
  - call `retry`
- `retry`
  - called by: `down|connect`
  - clear keepalive, cancel timer
  - call `retry_loop`
- `retry_loop`
  - schedule retry
  - receive `retry` message
  - call `connect|retry_loop`

So, I think I'm proposing this instead (again, roughly):
- `retry_init`
  - called by: `down`
  - clear keepalive, cancel timer
  - call `retry_loop(Delay=0)`
- `retry_continue`
  - called by: `connect`
  - call `retry_loop(Delay=RetryTimeout)`
- `retry_loop(Delay)`
  - schedule message after `Delay`
  - receive `retry` message
  - call `connect|retry_loop(Delay)`

Thoughts?

**Comment by essen** [comment]
I'm not sure about the proposal, sounds like a bigger change than needs to be, but otherwise yes, good point.

**Comment by unix1** [comment]
Sure, I was basically splitting the function in 2 to decouple the logic, but I'll leave it to you if you have a better way.

Also as a side note, while looking back at this, I noticed another bug (in both current and proposed) - if we get a system message before retry, we'll schedule another `retry` message before handling the one we already have. So that's possibly an argument for making even smaller functions.

**Comment by essen** [comment]
Done locally, push soon, thanks!
