### ISSUE TITLE
Some problem with ok = gun:ws_send(ConnPid, {text, "Hello"})

### ISSUE THREAD

**Issue by skvamme** [ninenines/gun#80]
I get: {'DOWN',#Ref<0.0.0.60>,process,<0.62.0>,badarg}

Sending ok = gun:ws_send(ConnPid, {binary, Bin}) works fine.

I'm not really good at erlang, probably doing something stupid.

**Comment by skvamme** [comment]
Cowboy side says:
In websocket_terminate: {error,closed}

**Comment by essen** [comment]
I need more info than that, like code for example. Badarg is a pretty common error.

**Comment by skvamme** [comment]
init() ->
	io:format("New process: ~p~n", [?MODULE]),
	{ok, ConnPid} = gun:open("192.168.0.101", 8080),
	_MRef = monitor(process, ConnPid),
	{ok, _Protocol} = gun:await_up(ConnPid),
	gun:ws_upgrade(ConnPid, "/wsh"),
...
receive
		{gun_ws_upgrade,ConnPid,ok,_} -> io:format("Websocket is up~n",[]),
			ok = gun:ws_send(ConnPid, {binary, <<"Hello">>}), % Works ok
			ok = gun:ws_send(ConnPid, {text, "Hello"}), % Don't work
			?MODULE:loop(Port1,Port2,ConnPid,up,[C1,C2,C3],C4,Gx);

...

And on Cowboy side:
In ws_handler_2 {binary,<<"Hello">>}
In websocket_terminate: {error,closed}


Same result on both erlang v17.4 and 18.0

**Comment by essen** [comment]
Please reopen if this is still an issue. Thanks!
