### ISSUE TITLE
{error,closed} in Cowboy even if I do an gun:shutdown(ConnPid)

### ISSUE THREAD

**Issue by skvamme** [ninenines/gun#81]
Possibly a Cowboy issue, but I get an {error,closed} message in Cowboy when I call gun:shutdown(ConnPid) in Gun. Imho this is not an error. Or is there a way to close down the websocket without causing an error in Cowboy?

**Comment by essen** [comment]
gun:shutdown isn't actually implemented yet, I think. :-)

**Comment by skvamme** [comment]
:-)

**Comment by skvamme** [comment]
Until it's implemented, this works fine:
gun:ws_send(ConnPid, close), gun:close(ConnPid), 

Gives a nice {remote,closed} in Cowboy.
