### ISSUE TITLE
ws_upgrade error 

### ISSUE THREAD

**Issue by MerkerXu** [ninenines/gun#84]
hello, I meet a timeout error when using **gun:ws_upgrade** on web server Cowboy. I seems similar to https://github.com/ninenines/gun/issues/36, except I got nothing on the server side log.
Here is the code snippet: 
<pre><code>
ws() ->
    application:ensure_all_started(gun),
    {ok, Pid}  = gun:open("127.0.0.1", 8090, #{retry=>0}),
    {ok, http} = gun:await_up(Pid),
    %%monitor(process, Pid),
    gun:ws_upgrade(Pid, "/ws", [], #{compress => true}),
    receive
        {gun_ws_upgrade, Pid, ok, Headers} ->
            io:format("~p ~p~n", ["Success", Headers]);
        Msg ->
            exit({ws_upgrade_failed, Msg})
    after 1000 ->
        exit(timeout)
    end,
    gun:close(Pid),
    application:stop(gun). 
</code></pre>

When I uncomment the monitor line,  it report a undef error
<pre><code>
1> testgun:ws().
** exception exit: {ws_upgrade_failed,{'DOWN',#Ref<0.0.2.67>,process,<0.55.0>,
                                              undef}}
     in function  testgun:ws/0 (src/testgun.erl, line 48)
</code></pre>

So what is the problem here, any help will be appreciated, thanks.

**Comment by essen** [comment]
Hmm 'undef' sounds like something is wrong in gun itself, or perhaps in the dependencies.

Gun requires cowlib 1.3.0+ for Websocket support, which is not compatible with Cowboy 1.0 for example. Could you be running the wrong cowlib issue? Another possible issue is that your Gun is outdated and doesn't have the Websocket support yet, as the interface was there long before the implementation.

**Comment by MerkerXu** [comment]
thanks, after upgrading ranch to the latest version, everything went ok now.

**Comment by essen** [comment]
Glad to hear. Closing, thanks!
