### ISSUE TITLE
Publish on hex.pm?

### ISSUE THREAD

**Issue by duijf** [ninenines/gun#88]
Hello!

I am wanting to use this project in an Elixir codebase, however, it is not published on [hex.pm]. Are you open to publishing this to hex?

Since rebar3 has support for hex, it means you can publish without having to include Elixir code in this project. Basically, the only thing that needs to happen is for `src/gun.app.src` to be updated like this:

```erlang
{application, gun, [
    {description, "Asynchronous SPDY, HTTP and Websocket client."},
    {vsn, "1.0.0-pre.1"},
    {modules, []},
    {registered, [gun_sup]},
    {applications, [
        kernel,
        stdlib,
        ranch,
        cowlib,
        ssl
    ]},
    {mod, {gun_app, []}},
    {env, []},
    {maintainers, ["Loïc Hoguin"]},
    {licenses, ["ISC"]},
    {links, [{"Github", "https://github.com/ninenines/gun"}]}
]}.
```

And then published to hex.pm with `rebar3 hex publish` (after installing the hex rebar plugin, for more info see [here](https://hex.pm/docs/rebar3_publish)).

Your build system does not need to change. AFAIK only the metadata needs to be added.

Are you open to publishing on hex? If not, would you mind if I'd make it available there?

 [hex.pm]:https://hex.pm/

**Comment by essen** [comment]
I don't use rebar, and the .app.src will disappear from the project the next time I update it.

You can make it available there as long as my involvement is not necessary.

**Comment by essen** [comment]
Closing for now, feel free to ping me if you make it available there. Thanks!

**Comment by duijf** [comment]
Will do! Thanks for your reply (missed the notification). Going to work on it this weekend
