### ISSUE TITLE
`transfer-encoding: chunked` with content-length header does not de-chunk

### ISSUE THREAD

**Issue by fp** [ninenines/gun#92]
When the server sends a response (for example from cowboy) that is has a `content-length` head present when then `transfer-encoding` is set to `chunked`, then gun fails to decode the reply as chunked and simply passes through the whole things as `{gun_data, ...}` tuples, including the chunked separators.

Looking at [HTTP RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616.txt) it appears that this is a MUST NOT condition on the server, as well as a MUST on the client (4.4, bullet 3):

> If a Content-Length header field (section 14.13) is present, its
> decimal value in OCTETs represents both the entity-length and the
> transfer-length. The Content-Length header field MUST NOT be sent
> if these two lengths are different (i.e., if a Transfer-Encoding
> header field is present). If a message is received with both a
> Transfer-Encoding header field and a Content-Length header field,
> the latter MUST be ignored.

So gun should ignore the `content-length` header in the presence of `transfer-encoding: chunked`.

I will add the corresponding Issue to cowboy as well, and try to send a PR(s) to address these over the holidays.

**Comment by essen** [comment]
Follow RFC7230 instead.

It does say the same. In Gun it's probably a bug. In Cowboy you need to call the chunked_reply function, and Cowboy does not do any check (maybe it would in the future after I finish the RFC7230 test suite, but I'm not quite there yet).

**Comment by fp** [comment]
I'll double check on 7230 before submitting anything.

On the cowboy side, I think that simply removing the `content-length` leader if passed in the `cowboy_req:chunked_reply` function follows along with the other practices in the library with respect to headers.

Anyway, I'm building a proxy using cowboy and gun (btw, very nicely done) and ran into this bug on my side, which look like guard rails that can be put into both to help avoid the issue in the future.

**Comment by essen** [comment]
Yeah. Do add a test to the rfc7230 suite though (in Cowboy). It shouldn't be too difficult, there's lots of examples. For Gun, no such suite yet, so no test is OK for now, though feel free to start one similar to the SPDY one.

**Comment by eapesa** [comment]
Hi,

May I know if there's a known fix for this or any short term solution?

**Comment by essen** [comment]
Patches welcome.

**Comment by essen** [comment]
Done locally, push soon!
