### ISSUE TITLE
http2 :status check doesn't seem to account for multiple headers blocks

### ISSUE THREAD

**Issue by philipstears** [ninenines/gun#96]
So, I think I've found an issue with the way that gun enforces RFC7540 8.1.2.4 (the requirement that every response includes a :status header) at https://github.com/ninenines/gun/blob/master/src/gun_http2.erl#L109.

As far as I can tell, this is validated for every headers block, rather than once for the entire response.

I'm testing against an http2 server which is sending a headers block, then data, and then another headers block, which causes gun to reset the stream because although the first headers block includes :status, the final one does not.

I've had a skim of the relevant section of the spec and it seems to indicate that once-per-response is the correct behaviour, rather than once-per-block.

**Comment by essen** [comment]
I think I haven't done the handling of trailer headers yet.

**Comment by philipstears** [comment]
That explains that; my apologies for the spurious ticket in that case.

**Comment by essen** [comment]
No worries, that's good to know since I wouldn't have implemented it for a long time otherwise.

**Comment by essen** [comment]
There probably isn't enough validation of malformed responses in the current code but it now supports trailers and expects those to not have a :status. I'll close for now and expect future tests to improve the validation of malformed responses.
